### ISSUE TITLE
Clean up deprecated github team

### ISSUE THREAD

**Issue by PatrickXYS** [kubeflow/internal-acls#403]
Given some GitHub team we established previously is not in use or deprecated,

the list of data points I can collect:

1. @kubeflow/kfctl-release  
2. @kubeflow/project-maintainers 
3. @kubeflow/release-planning 

We should clean up those deprecated github team to formalize permission granting, given now we have WG, which should be folks who have write access to the repo, only a few other folks should have write access to the repo, e.g, release-team, google-admins, etc.

/cc @Bobgy @Jeffwan @jlewi

**Comment by Bobgy** [comment]
SGTM
/cc @kubeflow/wg-deployment-leads 
/cc @jbottum 

What do you think?

**Comment by Jeffwan** [comment]
`kfctl-release` was created in last release. The reason is we want to grant minimum permission to folks helping on the kfctl release. `release-team` manages lots of repos which is too wide. I think this is no longer needed. WG-deployment leads should have write permission now. 

for rest of them, we need to get some feedbacks from PM as well

**Comment by PatrickXYS** [comment]
@Jeffwan Right, given we now have @kubeflow/wg-deployment-leads take care of kfctl release, I think @kubeflow/kfctl-release is not yet needed.

For `release team`, I think giving kubeflow/kubeflow write access make sense, the team can create new kanban there.

For `project-maintainers` team, which is created to take care of Kanban, given now we have WG, this should be deprecated as well.

**Comment by jlewi** [comment]
+1 to getting rid of project-maintaieners. The genesis of that group was that you need write permission on a repo in order to be able to tag an issue into an org-level project. So in order to build the Kanban boards for Kubeflow 1.X, whoever was tagging the issues into the Kanban board needed write access to all such issues.
